name: Build Kernel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Get the source code
    - name: Checkout code
      uses: actions/checkout@v4
      
    # 2. Install build dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          clang \
          lld \
          ninja-build \
          llvm
          
    # 3. Build the kernel using ninja
    - name: Build kernel
      run: ninja
      
    # 4. Verify that we produced a valid ELF
    - name: Verify kernel artifact
      run: |
        ls -la kernel.elf
        file kernel.elf
        readelf -h kernel.elf
        
    # 5. Save the kernel for download/debugging
    - name: Upload kernel artifact
      uses: actions/upload-artifact@v4
      with:
        name: kernel-elf
        path: kernel.elf
        retention-days: 30
